runtime: python39  # Specify the Python runtime version

entrypoint: gunicorn -b :$PORT app:app

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto

env_variables:
  # Define environment variables here if needed
  # Example:
  # FLASK_ENV: 'production'

# Optional: Configure instance class
# instance_class: F2
